import type { ActivityEvent, AgentTask, Device, McpServerStatus } from "@/types";

const now = Date.now();
const minutesAgo = (minutes: number) => new Date(now - minutes * 60_000).toISOString();

export const mockDevices: Device[] = [
  {
    id: "pixel-9-pro",
    deviceId: "MOB-9F2A-71D4",
    name: "Pixel 9 Pro",
    type: "mobile",
    os: "Android",
    osVersion: "16",
    status: "online",
    permittedIp: "203.0.113.24",
    appVersion: "3.8.1",
    mcpConnection: "connected",
    agentConnection: "connected",
    activeTasks: 2,
    lastActivity: minutesAgo(1),
    lastSeen: minutesAgo(1),
  },
  {
    id: "studio-mac",
    deviceId: "DSK-47B8-19CE",
    name: "Studio Mac",
    type: "desktop",
    os: "macOS",
    osVersion: "26.0",
    status: "busy",
    permittedIp: "198.51.100.18",
    appVersion: "3.8.1",
    mcpConnection: "connected",
    agentConnection: "connected",
    activeTasks: 4,
    lastActivity: minutesAgo(2),
    lastSeen: minutesAgo(2),
  },
  {
    id: "thinkpad-x1",
    deviceId: "LTP-CA32-8F10",
    name: "ThinkPad X1 Carbon",
    type: "laptop",
    os: "Windows",
    osVersion: "11 Pro",
    status: "offline",
    permittedIp: "192.0.2.88",
    appVersion: "3.7.4",
    mcpConnection: "disconnected",
    agentConnection: "disconnected",
    activeTasks: 0,
    lastActivity: minutesAgo(340),
    lastSeen: minutesAgo(340),
  },
  {
    id: "iphone-16",
    deviceId: "MOB-E81C-553B",
    name: "iPhone 16",
    type: "mobile",
    os: "iOS",
    osVersion: "26.0",
    status: "reconnecting",
    permittedIp: "203.0.113.81",
    appVersion: "3.8.0",
    mcpConnection: "limited",
    agentConnection: "disconnected",
    activeTasks: 1,
    lastActivity: minutesAgo(5),
    lastSeen: minutesAgo(5),
  },
  {
    id: "framework-13",
    deviceId: "LTP-91D3-2AB6",
    name: "Framework Laptop 13",
    type: "laptop",
    os: "Fedora Linux",
    osVersion: "42",
    status: "disabled",
    permittedIp: "192.0.2.146",
    appVersion: "3.6.9",
    mcpConnection: "disconnected",
    agentConnection: "disconnected",
    activeTasks: 0,
    lastActivity: minutesAgo(1440),
    lastSeen: minutesAgo(1440),
  },
];

export const mockAgentTasks: AgentTask[] = [
  {
    id: "job_a1b2c3",
    deviceId: "pixel-9-pro",
    deviceName: "Pixel 9 Pro",
    instruction: "Summarize today’s build notifications",
    status: "completed",
    createdAt: minutesAgo(120),
    completedAt: minutesAgo(118),
  },
  {
    id: "job_d4e5f6",
    deviceId: "studio-mac",
    deviceName: "Studio Mac",
    instruction: "Review the latest test run and prepare a concise report",
    status: "running",
    createdAt: minutesAgo(30),
  },
  {
    id: "job_g7h8i9",
    deviceId: "thinkpad-x1",
    deviceName: "ThinkPad X1 Carbon",
    instruction: "Collect the last successful deployment version",
    status: "failed",
    createdAt: minutesAgo(600),
    completedAt: minutesAgo(598),
  },
  {
    id: "job_j1k2l3",
    deviceId: "iphone-16",
    deviceName: "iPhone 16",
    instruction: "Queue a secure sync when the connection recovers",
    status: "pending",
    createdAt: minutesAgo(2),
  },
];

export const mockActivity: ActivityEvent[] = [
  { id: "act_1", message: "MCP session refreshed successfully", severity: "success", source: "Studio Mac", timestamp: minutesAgo(4) },
  { id: "act_2", message: "Connection lost; retrying in the background", severity: "error", source: "ThinkPad X1 Carbon", timestamp: minutesAgo(340) },
  { id: "act_3", message: "Agent task queued: summarize build notifications", severity: "info", source: "Pixel 9 Pro", timestamp: minutesAgo(30) },
  { id: "act_4", message: "Network handoff detected; reconnecting", severity: "warning", source: "iPhone 16", timestamp: minutesAgo(0) },
  { id: "act_5", message: "Companion app update installed successfully", severity: "success", source: "Pixel 9 Pro", timestamp: minutesAgo(1440) },
];

export const mockMcpServers: McpServerStatus[] = [
  { id: "mcp_1", name: "Connected Devices MCP", endpoint: "/api/mcp", connected: true, toolCount: 4, lastPing: minutesAgo(0) },
];
